proxy_intercept_errors on;
fastcgi_intercept_errors on;

error_page 502 503 504 = @global_50x;
error_page 404 = @global_404;

client_header_buffer_size 16k;
large_client_header_buffers 4 64k;

location @global_50x {
    root /custom_errors;
    try_files /50x.html =502;
    internal;
}

location @global_404 {
    root /custom_errors;
    try_files /404.html =404;
    internal;
}